<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next Step   please wait</name>
   <tag></tag>
   <elementGuidId>7148dfcf-2529-4264-a86b-ffe6f64f7270</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-register']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn-register</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1f067471-6c79-479f-838c-a577ac50945d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-register</value>
      <webElementGuid>4121d440-7557-427e-b428-648036553117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d6cb75d4-ac32-4921-b91a-a43dde29f43f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-create-account btn btn-block</value>
      <webElementGuid>8d57a4d1-3853-4538-a624-f3aa42d2ec98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next Step   please wait </value>
      <webElementGuid>cf654263-2372-432c-b1c6-52b99cadd60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-register&quot;)</value>
      <webElementGuid>a537dfaa-cf1c-421a-b5c4-1ef219c87349</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-register']</value>
      <webElementGuid>d1a2b27f-0fee-4eac-898e-3917c883b34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formRegister']/div[7]/div[2]/button</value>
      <webElementGuid>28c9ff11-6794-4567-99d1-3b49f611b57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Privacy Statement'])[1]/following::button[1]</value>
      <webElementGuid>014574e4-9f22-4f5a-8273-8f717f772481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Terms &amp; Conditions'])[1]/following::button[1]</value>
      <webElementGuid>3ee1a3a9-c131-4588-ba6f-1feae6d83479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next Step']/parent::*</value>
      <webElementGuid>806360dc-f698-4e55-9ec7-2460c3043e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/button</value>
      <webElementGuid>47128eaf-062b-48fe-8686-d5d2fbaf05f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn-register' and @type = 'submit' and (text() = 'Next Step   please wait ' or . = 'Next Step   please wait ')]</value>
      <webElementGuid>6e315e29-4dd2-4386-af7f-8a6ffc5ed238</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
